POST http://localhost:8000/transfer HTTP/1.1
content-type: application/json

{
  "originAccountId": "cc8b43ca-207f-4b73-be25-9b8c194ee5f8",
  "destinationAccountId": "ea2bcb8d-fd48-483f-8a15-763d40a0c360",
  "amount": 10
}
