POST http://localhost:8000/user/create HTTP/1.1
content-type: application/json

{
    "firstName": "teste",
    "lastName": "teste",
    "document": "99999999999",
    "email": "teste@gmail.com",
    "password": "12345678",
    "types": "COMMON"
}
